name: theoffice

dependencies:
- python=3.6
- matplotlib=2.1.2
- jupyter=1.0.0
- numpy=1.14.2
- pandas=0.22.0
- scipy=1.0.1
- pytest=3.5.0
- scikit-learn=0.19.1
- scrapy=1.5.0
- beautifulsoup4=4.6.0
- jupyterlab=0.32.1
- lxml=4.2.1
- seaborn=0.8.1
